window.data20 = [
  [
    [
      {
        votes: 3,
        original: true,
        from: 0
      }, {
        votes: 0,
        from: 0
      }, {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 0,
        from: 1
      }, {
        votes: 3,
        original: true,
        from: 2
      }, {
        votes: 0,
        from: 2
      }, {
        votes: 1,
        original: true,
        from: 3
      }, {
        votes: 0,
        from: 3
      }, {
        votes: 4,
        original: true,
        from: 4
      }, {
        votes: 0,
        from: 4
      }, {
        votes: 1,
        original: true,
        from: 5
      }, {
        votes: 0,
        from: 5
      }, {
        votes: 1,
        original: true,
        from: 6
      }, {
        votes: 0,
        from: 1
      }, {
        votes: 2,
        original: true,
        from: 7
      }, {
        votes: 0,
        from: 7
      }, {
        votes: 17,
        original: true,
        from: 8
      }, {
        votes: 0,
        from: 8
      }, {
        votes: 1,
        original: true,
        from: 9
      }, {
        votes: 0,
        from: 9
      }, {
        votes: 2,
        original: true,
        from: 10
      }, {
        votes: 0,
        from: 10
      }, {
        votes: 7,
        original: true,
        from: 11
      }, {
        votes: 0,
        from: 11
      }, {
        votes: 1,
        original: true,
        from: 12
      }, {
        votes: 0,
        from: 12
      }, {
        votes: 2,
        original: true,
        from: 13
      }, {
        votes: 0,
        from: 13
      }, {
        votes: 1,
        original: true,
        from: 14
      }, {
        votes: 0,
        from: 14
      }, {
        votes: 3,
        original: true,
        from: 15
      }, {
        votes: 0,
        from: 15
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 0,
        from: 16
      }, {
        votes: 1,
        original: true,
        from: 17
      }, {
        votes: 0,
        from: 17
      }, {
        votes: 1,
        original: true,
        from: 18
      }, {
        votes: 0,
        from: 18
      }, {
        votes: 2,
        original: true,
        from: 19
      }, {
        votes: 0,
        from: 19
      }
    ], [
      {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 0,
        to: 0
      }, {
        votes: 22,
        originalFrom: true,
        originalTo: true,
        from: 1,
        to: 1
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 3,
        to: 1
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 5,
        to: 1
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 14,
        to: 1
      }, {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 2,
        to: 2
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 9,
        to: 2
      }, {
        votes: 4,
        originalFrom: true,
        originalTo: true,
        from: 4,
        to: 4
      }, {
        votes: 2,
        originalFrom: true,
        originalTo: true,
        from: 7,
        to: 7
      }, {
        votes: 17,
        originalFrom: true,
        originalTo: true,
        from: 8,
        to: 8
      }, {
        votes: 2,
        originalFrom: true,
        originalTo: true,
        from: 10,
        to: 10
      }, {
        votes: 7,
        originalFrom: true,
        originalTo: true,
        from: 11,
        to: 11
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 12,
        to: 8
      }, {
        votes: 2,
        originalFrom: true,
        originalTo: true,
        from: 13,
        to: 13
      }, {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 15,
        to: 15
      }, {
        votes: 25,
        originalFrom: true,
        originalTo: true,
        from: 16,
        to: 16
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 6,
        to: 16
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 17,
        to: 16
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 18,
        to: 16
      }, {
        votes: 2,
        originalFrom: true,
        originalTo: true,
        from: 19,
        to: 19
      }
    ]
  ], [
    [
      {
        votes: 3,
        original: true,
        from: 0
      }, {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 3,
        from: 1
      }, {
        votes: 3,
        original: true,
        from: 2
      }, {
        votes: 1,
        from: 2
      }, {
        votes: 4,
        original: true,
        from: 4
      }, {
        votes: 2,
        original: true,
        from: 7
      }, {
        votes: 17,
        original: true,
        from: 8
      }, {
        votes: 1,
        from: 8
      }, {
        votes: 2,
        original: true,
        from: 10
      }, {
        votes: 7,
        original: true,
        from: 11
      }, {
        votes: 2,
        original: true,
        from: 13
      }, {
        votes: 3,
        original: true,
        from: 15
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 3,
        from: 16
      }, {
        votes: 2,
        original: true,
        from: 19
      }
    ], [
      {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 0,
        to: 0
      }, {
        votes: 22,
        originalFrom: true,
        originalTo: true,
        from: 1,
        to: 1
      }, {
        votes: 3,
        originalFrom: false,
        originalTo: false,
        from: 1,
        to: 1
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 13,
        to: 1
      }, {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 2,
        to: 2
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 2,
        to: 2
      }, {
        votes: 4,
        originalFrom: true,
        originalTo: true,
        from: 4,
        to: 4
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 13,
        to: 4
      }, {
        votes: 17,
        originalFrom: true,
        originalTo: true,
        from: 8,
        to: 8
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 8,
        to: 8
      }, {
        votes: 7,
        originalFrom: true,
        originalTo: true,
        from: 11,
        to: 11
      }, {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 15,
        to: 15
      }, {
        votes: 25,
        originalFrom: true,
        originalTo: true,
        from: 16,
        to: 16
      }, {
        votes: 3,
        originalFrom: false,
        originalTo: false,
        from: 16,
        to: 16
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 7,
        to: 16
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 10,
        to: 16
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 19,
        to: 16
      }
    ]
  ], [
    [
      {
        votes: 3,
        original: true,
        from: 0
      }, {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 4,
        from: 1
      }, {
        votes: 3,
        original: true,
        from: 2
      }, {
        votes: 1,
        from: 2
      }, {
        votes: 4,
        original: true,
        from: 4
      }, {
        votes: 1,
        from: 4
      }, {
        votes: 17,
        original: true,
        from: 8
      }, {
        votes: 1,
        from: 8
      }, {
        votes: 7,
        original: true,
        from: 11
      }, {
        votes: 3,
        original: true,
        from: 15
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 9,
        from: 16
      }
    ], [
      {
        votes: 22,
        originalFrom: true,
        originalTo: true,
        from: 1,
        to: 1
      }, {
        votes: 4,
        originalFrom: false,
        originalTo: false,
        from: 1,
        to: 1
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 0,
        to: 1
      }, {
        votes: 3,
        originalFrom: true,
        originalTo: true,
        from: 2,
        to: 2
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 2,
        to: 2
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 0,
        to: 2
      }, {
        votes: 4,
        originalFrom: true,
        originalTo: true,
        from: 4,
        to: 4
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 4,
        to: 4
      }, {
        votes: 17,
        originalFrom: true,
        originalTo: true,
        from: 8,
        to: 8
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 8,
        to: 8
      }, {
        votes: 1,
        originalFrom: true,
        originalTo: false,
        from: 0,
        to: 8
      }, {
        votes: 7,
        originalFrom: true,
        originalTo: true,
        from: 11,
        to: 11
      }, {
        votes: 25,
        originalFrom: true,
        originalTo: true,
        from: 16,
        to: 16
      }, {
        votes: 9,
        originalFrom: false,
        originalTo: false,
        from: 16,
        to: 16
      }, {
        votes: 3,
        originalFrom: false,
        originalTo: false,
        from: 15,
        to: 16
      }
    ]
  ], [
    [
      {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 5,
        from: 1
      }, {
        votes: 3,
        original: true,
        from: 2
      }, {
        votes: 2,
        from: 2
      }, {
        votes: 4,
        original: true,
        from: 4
      }, {
        votes: 1,
        from: 4
      }, {
        votes: 17,
        original: true,
        from: 8
      }, {
        votes: 2,
        from: 8
      }, {
        votes: 7,
        original: true,
        from: 11
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 12,
        from: 16
      }
    ], [
      {
        votes: 22,
        originalFrom: true,
        originalTo: true,
        from: 1,
        to: 1
      }, {
        votes: 5,
        originalFrom: false,
        originalTo: false,
        from: 1,
        to: 1
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 2,
        to: 1
      }, {
        votes: 1,
        originalFrom: false,
        originalTo: false,
        from: 4,
        to: 1
      }, {
        votes: 17,
        originalFrom: true,
        originalTo: true,
        from: 8,
        to: 8
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 8,
        to: 8
      }, {
        votes: 4,
        originalFrom: false,
        originalTo: false,
        from: 4,
        to: 8
      }, {
        votes: 5,
        originalFrom: false,
        originalTo: false,
        from: 11,
        to: 8
      }, {
        votes: 25,
        originalFrom: true,
        originalTo: true,
        from: 16,
        to: 16
      }, {
        votes: 12,
        originalFrom: false,
        originalTo: false,
        from: 16,
        to: 16
      }, {
        votes: 3,
        originalFrom: false,
        originalTo: false,
        from: 2,
        to: 16
      }, {
        votes: 2,
        originalFrom: false,
        originalTo: false,
        from: 11,
        to: 16
      }
    ]
  ], [
    [
      {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 8,
        from: 1
      }, {
        votes: 17,
        original: true,
        from: 8
      }, {
        votes: 11,
        from: 8
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 17,
        from: 16
      }
    ], [
      {
        votes: 22,
        originalFrom: true,
        originalTo: true,
        from: 1,
        to: 1
      }, {
        votes: 8,
        originalFrom: false,
        originalTo: false,
        from: 1,
        to: 1
      }, {
        votes: 13,
        originalFrom: false,
        originalTo: false,
        from: 8,
        to: 1
      }, {
        votes: 25,
        originalFrom: true,
        originalTo: true,
        from: 16,
        to: 16
      }, {
        votes: 17,
        originalFrom: false,
        originalTo: false,
        from: 16,
        to: 16
      }, {
        votes: 15,
        originalFrom: false,
        originalTo: false,
        from: 8,
        to: 16
      }
    ]
  ], [
    [
      {
        votes: 22,
        original: true,
        from: 1
      }, {
        votes: 21,
        from: 1
      }, {
        votes: 25,
        original: true,
        from: 16
      }, {
        votes: 32,
        from: 16
      }
    ], [

    ]
  ]
];

